### ISSUE TITLE
研究室成員頁面年級下拉式選單被切掉了

### ISSUE THREAD

**Issue by thejackshih** [berniechiu/lab_635#1]
畢業學長姐系級查詢的下拉式選單被切掉了，100只顯示1、99只顯示9。
瀏覽器
版本是Windows Chrome 45.0.2454.93 m

![issue](https://cloud.githubusercontent.com/assets/8075375/9894705/3d565584-5c59-11e5-8f09-b81ecd2df47b.png)

**Comment by berniechiu** [comment]
Seems to work fine.

<img width="854" alt="2015-09-16 15 01 54" src="https://cloud.githubusercontent.com/assets/2749593/9898318/ef1d2494-5c83-11e5-8ce1-16f3b5490424.png">

**Comment by thejackshih** [comment]
看起來像是寬度的問題，我電腦的解析度很低(1024x768) 實際拖拉後也有發生這樣的狀況。
![issue3](https://cloud.githubusercontent.com/assets/8075375/9923179/64ec6a68-5d24-11e5-96f6-933e0c3456c3.png)
以上寬度是在只比手機版面大一點的時候。

**Comment by berniechiu** [comment]
Fix in 89f80927e73876338b396bab36f290449f0657f7
